spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.metadata-map.github.repo=BrayanVanz/microservices_java

info.app.name=${spring.application.name}
info.app.description=Eureka discovery service
info.app.autor=Brayan Vanz de Oliveira